spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/qna?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rlaclgns5628

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: ture
        show_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.type.descriptor.sql: trace