spring:
  h2:
    console:
      ## SQLYog 같은 콘솔을 웹으로 제공되는게 있는데, 그것을 사용하겠다
      enabled: true
      ## 콘솔의 URL
      path: /h2-console
  datasource:
    ## DB 파일의 위치
#    url: jdbc:h2:tcp://localhost/~/local;MODE=MariaDB
    url: jdbc:h2:tcp://localhost/~/local
    ## 드라이버 클래스명
    driver-class-name: org.h2.Driver
    ## DB ID : sa 계정은 기본적으로 들어있다.
    username: sa
    ## DB PW : sa 계정의 비번, 보통 없음
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update